# Generated by Django 4.1.3 on 2023-01-15 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(default=datetime.datetime(2023, 1, 15, 16, 28, 25, 844094, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
